// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeNMJNhmOwpvFiI7EDDUtHsDVC541qHU',
    appId: '1:783748381221:web:7af3e7396a888b420c9dcc',
    messagingSenderId: '783748381221',
    projectId: 'lololand-20091',
    authDomain: 'lololand-20091.firebaseapp.com',
    storageBucket: 'lololand-20091.appspot.com',
    measurementId: 'G-C68R4LY3X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJOBtGB4yDrgmQPXbuqdho-1i4WipS3U',
    appId: '1:783748381221:android:bac2abe955db20e20c9dcc',
    messagingSenderId: '783748381221',
    projectId: 'lololand-20091',
    storageBucket: 'lololand-20091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHGv01jXnh0pTjHo6lLX3zoZa-VGwMqw',
    appId: '1:783748381221:ios:d4ff259709f5211a0c9dcc',
    messagingSenderId: '783748381221',
    projectId: 'lololand-20091',
    storageBucket: 'lololand-20091.appspot.com',
    iosBundleId: 'com.example.oathapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHGv01jXnh0pTjHo6lLX3zoZa-VGwMqw',
    appId: '1:783748381221:ios:d4ff259709f5211a0c9dcc',
    messagingSenderId: '783748381221',
    projectId: 'lololand-20091',
    storageBucket: 'lololand-20091.appspot.com',
    iosBundleId: 'com.example.oathapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMeNMJNhmOwpvFiI7EDDUtHsDVC541qHU',
    appId: '1:783748381221:web:0b3966e9a26d4e500c9dcc',
    messagingSenderId: '783748381221',
    projectId: 'lololand-20091',
    authDomain: 'lololand-20091.firebaseapp.com',
    storageBucket: 'lololand-20091.appspot.com',
    measurementId: 'G-7MGMXTHWBM',
  );
}
